name: Deployment

on:
  push:
    branches:
      - next 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        #deploy_key: ${{ secrets.DEPLOY_KEY }}
        publish_dir: ./out
        cname: dhruvang.com 

env:
  NODE_ENV: production
